package:
  name: pyqsar
  version: 1.0

source:
  git_rev: latest
  git_url: https://github.com/stephenszwiec/pyqsar

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
